/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function handlePlay(databaseUrl: string, cookieHeader: string | undefined | null, body: string): Promise<PlayResult>

export declare function hello(name: string): string

export interface PlayResult {
  status: number
  revalidationTags: Array<string>
}

export declare function proxyDecision(pathname: string, cookieHeader?: string | undefined | null): ProxyResult

export interface ProxyResult {
  redirectPathname?: string
}
